<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
    <PackageReference Include="Vortice.SPIRV.Reflect" Version="1.0.6" />
    <PackageReference Include="Vortice.Vulkan" Version="3.2.3" />
    <PackageReference Include="Vortice.VulkanMemoryAllocator" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.RHI\Engine.RHI.csproj" />
  </ItemGroup>

</Project>
